### PR TITLE
fix: multiple issues

### LINKED ISSUE #1: Tablist doesn't consistantly show all players
You can replicate this consistently when using /switch. This works normally when you join and stay on the same server. The tablist does not update when someone leaves until the player rejoins to update it.

### LINKED ISSUE #6: ‼️The original nether is not connected the secondary world.
The nether on the secondary world is not connected to the correct one. Instead of the correct nether a whole newly generated one is in place.
Regions also don't match. The regions currently in the nether are the same as the overworld.

### LINKED ISSUE #8: ⚠️Join and leave messages are inconsistant.
Join message work, but when someone fails to join, the message still go through but doesn't send it in the chat yet. It sends it in the chat all at once when a player successfully joins.
Leave messages don't show.

### LINKED ISSUE #23: ‼️‼️Inventories do not sync across worlds.
When one goes from Primary to Secondary, their inventories do not go with them. Both inventory and enderchest. This has top priority as it stops people from playing.

### PR DESCRIPTION
**Pull request by Vaalley**
supposed to fix #6 but it was actually just a directory issue. fixed though!

This also fixes #23 lol (not intended, but cool)

Also fixes #8 
and fix #1 (isn't fully fixed yet)

### CODE REVIEW

File: features/NotepadFeature.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ function buildWritableBookItem(pages: string[]): Buffer {
 function sendFakeBook(player: OnlinePlayer, pages: string[]): void {
   const socket = getPlayerSocket(player);
   if (!socket) {
-    console.log('[Notepad] No socket for player');
+    // console.log('[Notepad] No socket for player');
```
Comment (Blazzike) [inline features/NotepadFeature.ts]: let's just get rid of these logs instead of commenting them out I reckon!

File: network/proxy.ts [hunk 2]
```diff
@@ -42,7 +42,7 @@ function generateOfflineUUID(username: string): string {
 }
 
 export function broadcastPlayerJoin(uuid: string, username: string, excludeUuid?: string) {
-  const props = executeHookFirst(FeatureHook.GetProfileProperties, { uuid }) || [];
+  const props = (executeHookFirst(FeatureHook.GetProfileProperties, { uuid }) || []) as any[];
```
Comment (Blazzike) [inline network/proxy.ts]: possible not to use any[] here?

File: network/proxy.ts [hunk 3]
```diff
@@ -81,12 +81,14 @@ function sendGlobalTabList(targetPlayer: any) {
   const players = executeHookFirst<OnlinePlayer[]>(FeatureHook.GetOnlinePlayers) || [];
   if (players.length === 0) return;
 
+  const socket = getPlayerSocket(targetPlayer);
+  if (!socket) return;
+
   for (const player of players) {
-    const props = executeHookFirst(FeatureHook.GetProfileProperties, { uuid: player.uuid }) || [];
+    const props = (executeHookFirst(FeatureHook.GetProfileProperties, { uuid: player.uuid }) || []) as any[];
```
Comment (Blazzike) [inline network/proxy.ts]: and here!

File: network/proxy.ts (hunk 2 above)
Comment (Blazzike) [reply network/proxy.ts]: should probs be ?? not || too!
